---
title: "Exploratory Plots"
output: pdf_document
---

```{r include = FALSE}
library(tidyverse)
library(gridExtra)
data <- read_csv("https://raw.github.ubc.ca/MDS-2018-19/DSCI554_project_DavyGuo/master/clean_data.csv?token=AAAGlHbiHxOKw8NAICYyMJ1ejrA9kkrTks5cr2rYwA%3D%3D")
```


```{r coding plots, echo = FALSE}
data$coding <- fct_relevel(data$coding, 
                           "high",
                           "moderate",
                           "average",
                           "low",
                           "none")
coding_stress <- data %>% 
  ggplot(aes(y = stress, x = coding)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.5) +
  ggtitle("Coding Skill vs. Stress Level") +
  xlab("coding skill") +
  theme_bw()


coding_os <- data %>% 
  ggplot(aes(x = coding)) +
  geom_bar(aes(fill = os )) +
  scale_fill_viridis_d(name = "") +
  ggtitle("Coding Skill vs Operating System") +
  xlab("coding skill") +
  theme_bw() 

grid.arrange(coding_stress, coding_os, nrow = 2)
```  



```{r age plots, echo = FALSE}
age_stress <- data %>% 
  filter(age < 40, age > 20) %>% 
  ggplot(aes(x = age, y = stress)) +
  geom_jitter(alpha = 0.5) +
  theme_bw() +
  ggtitle("Age vs. Stress Level")

age_os <- data %>% 
  filter(age < 40, age > 20) %>% 
  ggplot(aes(y = age, x = os)) +
  geom_boxplot()+
  geom_jitter(alpha = 0.5) +
  theme_bw() +
  ggtitle("Age vs. Operating System") +
  xlab("")

grid.arrange(age_stress, age_os, ncol = 2)
```  
```{r experience plots, echo = FALSE}
experience_stress <- data %>% 
  ggplot(aes(x = work_year, y = stress)) +
  geom_jitter(alpha = 0.5) +
  theme_bw() +
  xlab("years of work experience") + 
  ggtitle("Experience vs. Stress Level")

experience_os <- data %>% 
  ggplot(aes(y = work_year, x = os)) +
  geom_boxplot()+
  geom_jitter(alpha = 0.5) +
  theme_bw() +
  ylab("years of work experience") + 
  xlab("") +
  ggtitle("Experience vs. Operating System") 

grid.arrange(experience_stress, experience_os, ncol = 2)
```

```{r gender plots, echo = FALSE}

gender_stress <- data %>% 
  ggplot(aes(y = stress, x = gender)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.5) +
  theme_bw() +
  ggtitle("Gender vs. Stress Level")

gender_os <- data %>% 
  ggplot(aes(gender)) +
  geom_bar(aes(fill = os)) +
  scale_fill_viridis_d(name = "") +
  theme_bw() +
  ggtitle("Gender vs. Operating System")

grid.arrange(gender_stress, gender_os, ncol = 2)
  

```  

```{r background blots, echo = FALSE}

background_stress <- data %>%
  ggplot(aes(x = background, y = stress)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.5) +
  xlab("") +
  coord_flip() +
  theme_bw() +
  ggtitle("Background vs. Stress Level")

background_os <- data %>% 
  ggplot(aes(x = background)) +
  geom_bar(aes(fill = os )) +
  scale_fill_viridis_d(name = "") +
  ggtitle("Background vs. Operating System") +
  xlab("") +
  coord_flip() +
  theme_bw() 
grid.arrange(background_stress, background_os)
```



