---
title: "Methods Section"
author: "Alden Chen"
date: '2019-04-10'
output: pdf_document
---

## Methods

##### Survey Study Design

Our survey asks respondents what operating system they use on their laptop (Linux, Mac, or Windows) and  what their level of stress is on a scale from 0 to 10, where 0 represents "little or no stress" and 10 represents "a great deal of stress." The remaining questions targetted what we thought could be potential confounders: age, work experience, gender, self-reported coding proficiency, and academic background. 

For work experience and age we asked users to enter a number, rather than having pre-determined bins. We did this so that we could have more detailed data for our analysis. For academic background, we chose to provide some pre-specified categories to simplify data wrangling later. Coding proficiency was also rated on a scale. In order to preserve survey respondents' anonymity, we gave them a "prefer not to say" option for questions about age, work experience, and gender. 

##### Data Collection  

We collected the survey data using the UBC-hosted version of Qualtrics, as recommended by the UBC Office of Research Ethics. We sent the survey out to MDS students during lab time and received 52 responses. 

##### Analysis Methods

After cleaning the data, we produced some exploratory plots to see if there was a relationship between operating system and stress and to see if the potential confounders had any association with operating system or stress.  

To determine if operating system affects stress level, we fit linear regression and proportional odds models and tested the significance of `os`. 



